version: '2'
services:
  bot:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run dev:bot
    env_file: .env.dev
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://root:root@mongo
  mongo:
    image: mongo:4.2.12-bionic
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongo: {}